services:
     DB:
        image:  postgres:latest
        ports:
                -  "1521:5432"
        environment:
                - POSTGRES_HOST_AUTH_METHOD=trust
                - POSTGRES_PASSWORD=microcare
        container_name:  DB

     WEB:
         image: nginx:latest
         ports:
               - "7799:80"
         container_name: WEB1
         volumes:
               - "compose_new_vol:/opt/composer/"
         depends_on:
               - "DB"
               - "MID"
     MID:
         build: ./
         image: hari16008/new_image:latest
         ports:
               - "7798:80"
         container_name: MID1
         volumes:
               - "compose_new_vol:/opt/MID/"
volumes:
         compose_new_vol:
               name: compose_new_vol
               external: false
          
